name: moni
description: Assesment For Moni
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: DM
      fonts:
        - asset: assets/fonts/DMSans/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans/DMSans-Italic.ttf
          style: italic
        - asset: assets/fonts/DMSans/DMSans-Bold.ttf
          weight: 700